# gitpod.io/#github.com/CaravanaCloud/RedHatNotebooks
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Jupyter Notebook
    command: jupyter notebook
  
  - name: Salute!
    command: echo hello world!

ports:
  - port: 5000
  - port: 8080
  - port: 8888

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
#    - GitHub.copilot

