name: Create cluster and test it

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: string
        description: Dry run safety flag to disable writes
        required: false
        default: 'true'
      test_suite:
        type: string
        description: Test suite to execute on openshift-test
        required: false
        default: 'openshift/conformance/serial' 
              #  'openshift/conformance/parallel'

jobs:
  create_ocp_aws_ipi:
    uses: CaravanaCloud/RedHatNotebooks/.github/workflows/create_ocp_aws_ipi.yml@main
    with:
      dry_run: ${{ github.event.inputs.dry_run }}
    secrets:  
      PULL_SECRET: ${{ secrets.PULL_SECRET }}
      OCP_BASE_DOMAIN: ${{ secrets.OCP_BASE_DOMAIN }}
      OCP_SSH_KEY: ${{ secrets.OCP_SSH_KEY }}
      OCP_AWS_REGION: ${{ secrets.OCP_AWS_REGION }}
      OCP_AWS_ACCESS_KEY_ID: ${{ secrets.OCP_AWS_ACCESS_KEY_ID }}
      OCP_AWS_SECRET_ACCESS_KEY: ${{ secrets.OCP_AWS_SECRET_ACCESS_KEY }}
      FILE_KEY: ${{ secrets.FILE_KEY }}

  test_ocp:
    uses: CaravanaCloud/RedHatNotebooks/.github/workflows/test_ocp.yml@main
    with:
      dry_run: ${{ github.event.inputs.dry_run }}


