name: Create cluster and query it

on:
  workflow_dispatch: {}

jobs:
  create_ocp_aws_ipi:
    uses: CaravanaCloud/RedHatNotebooks/.github/workflows/create_ocp_aws_ipi.yml@main
    secrets:  
      PULL_SECRET: ${{ secrets.PULL_SECRET }}
      OCP_BASE_DOMAIN: ${{ secrets.OCP_BASE_DOMAIN }}
      OCP_SSH_KEY: ${{ secrets.OCP_SSH_KEY }}
      OCP_AWS_REGION: ${{ secrets.OCP_AWS_REGION }}
      OCP_AWS_ACCESS_KEY_ID: ${{ secrets.OCP_AWS_ACCESS_KEY_ID }}
      OCP_AWS_SECRET_ACCESS_KEY: ${{ secrets.OCP_AWS_SECRET_ACCESS_KEY }}
  print_version:
    needs: create_ocp_aws_ipi
    runs-on: ubuntu-latest  
    steps:
      - name: Print cluster name
        run: echo "CLUSTER_NAME=${{ needs.create_ocp_aws_ipi.outputs.cluster_name }}"

      - name: Download install-dir
        uses: actions/download-artifact@v3
        with:
          name: install-dir
          path: install-dir
      
      - name: Print the versions
        run: oc version
        env:
          KUBECONFIG: ./install-dir/auth/kubeconfig

      - name: Debug stuff
        run: find .
