name: Provision cluster using OCP IPI

on: [workflow_call,workflow_dispatch]

jobs:
  all-steps:
    runs-on: ubuntu-latest
    
    outputs:
      cluster_name: ${{ steps.generate-cluster-name.outputs.value }}

    steps:
      - id: generate-cluster-name
        run: echo "::set-output name=value::rhnb-$RANDOM"

      - name: Debug Variables
        run: echo "CLUSTER_NAME=$CLUSTER_NAME"
        env:
          CLUSTER_NAME: ${{ steps.generate-cluster-name.outputs.value }}
      
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Generate install config
        run: env
        env:
          INSTALL_DIR: "/tmp/install-dir"
          INSTALL_CONFIG: "/tmp/install-dir/install-config.yaml"
          