name: Provision cluster using OCP IPI

on: [workflow_call,workflow_dispatch]


jobs:
  all-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Say hi
        run: echo "Hi"

